# Workspace
workspace 1 output DP-1

# Bar
set $barfontsize 11
set $barheight 27
set $labelmode ~/.config/sway/handlers/metrics-desktop.sh

# Set Theme
include ~/.config/sway/themes/linux.conf # black

# Media
bindsym XF86MonBrightnessUp exec OP=d+ BF=$bf ~/.config/sway/handlers/media.sh
bindsym XF86MonBrightnessDown exec OP=d- BF=$bf ~/.config/sway/handlers/media.sh

bindsym $mod+Pause exec OP=d+ BF=$bf ~/.config/sway/handlers/media.sh
bindsym $mod+Scroll_Lock exec OP=d- BF=$bf ~/.config/sway/handlers/media.sh

bindsym XF86AudioRaiseVolume exec OP=v+ VF=$vf ~/.config/sway/handlers/media.sh
bindsym XF86AudioLowerVolume exec OP=v- VF=$vf ~/.config/sway/handlers/media.sh
bindsym XF86AudioMute exec OP=v0 ~/.config/sway/handlers/media.sh

# Keyboard Layout Switcher
bindsym $mod+Shift+Tab exec ~/.config/sway/handlers/keyboard-switch-layout.sh

# Set stuff for my monitor
output DP-1 {
    mode 1920x1080@165Hz
    position 0 0
    adaptive_sync on
}

#wallpaper
output * bg ~/.config/sway/imgs/wall6 fill

# I use this agent, you can use anything you want
exec /usr/bin/lxqt-policykit-agent

# For Hubstaff (job stuff)
exec dbus-send --session \
  --print-reply=literal \
  --dest=org.freedesktop.impl.portal.PermissionStore \
  /org/freedesktop/impl/portal/PermissionStore \
  org.freedesktop.impl.portal.PermissionStore.SetPermission \
  string:'screenshot' \
  boolean:'true' \
  string:'screenshot' \
  string:'netsoft-com.netsoft.hubstaff' \
  array:string:'yes'
