workspace 1 output DP-1

set $barfontsize 11
set $barheight 27
set $labelmode ~/.config/sway/handlers/metrics-desktop.sh

include ~/.config/sway/themes/linux.conf

bindsym XF86MonBrightnessUp exec OP=d+ BF=$bf ~/.config/sway/handlers/media.sh
bindsym XF86MonBrightnessDown exec OP=d- BF=$bf ~/.config/sway/handlers/media.sh

bindsym $mod+Pause exec OP=d+ BF=$bf ~/.config/sway/handlers/media.sh
bindsym $mod+Scroll_Lock exec OP=d- BF=$bf ~/.config/sway/handlers/media.sh

bindsym XF86AudioRaiseVolume exec OP=v+ VF=$vf ~/.config/sway/handlers/media.sh
bindsym XF86AudioLowerVolume exec OP=v- VF=$vf ~/.config/sway/handlers/media.sh
bindsym XF86AudioMute exec OP=v0 ~/.config/sway/handlers/media.sh

bindsym $mod+Shift+Tab exec ~/.config/sway/handlers/keyboard-switch-layout.sh

output DP-1 {
    mode 1920x1080@165Hz
    position 0 0
    adaptive_sync on
}

output * bg ~/.config/sway/imgs/wall5 fill

exec /usr/bin/lxqt-policykit-agent
#exec dbus-update-activation-environment --all
exec dbus-send --session \
  --print-reply=literal \
  --dest=org.freedesktop.impl.portal.PermissionStore \
  /org/freedesktop/impl/portal/PermissionStore \
  org.freedesktop.impl.portal.PermissionStore.SetPermission \
  string:'screenshot' \
  boolean:'true' \
  string:'screenshot' \
  string:'netsoft-com.netsoft.hubstaff' \
  array:string:'yes'
