exec_always cp ~/.config/foot/themes/blacky.ini ~/.config/foot/foot.ini
exec_always echo '@theme "~/.config/rofi/themes/blacky"' >& ~/.config/rofi/config.rasi

bar {
    swaybar_command waybar
}


# bar {
#   position top
#   font pango:Terminus Bold $barfontsize
#   height $barheight
#
#   # Label metrics
#   status_command $labelmode
#
#   colors {
#     statusline #d3d7cf
#     background #000000
#     inactive_workspace #000000 #000000 #d3d7cf
#     focused_workspace #ffffff #000000 #ffffff
#     active_workspace #d3d7cf #000000 #d3d7cf
#   }
# }



#gtk themes
set $gnome-schema org.gnome.desktop.interface
seat seat0 xcursor_theme 'winsur' 16

exec_always {
  gsettings set $gnome-schema gtk-theme 'darkest'
  gsettings set $gnome-schema icon-theme 'dark'
  gsettings set $gnome-schema cursor-theme 'winsur'
  gsettings set $gnome-schema cursor-size '16'
  #gsettings set $gnome-schema font-name 'Ubuntu 12'
}
